stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    - PULL_RESULT=""
    - docker pull registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:arm-latest && PULL_RESULT="ok"
    - if [ "$PULL_RESULT" == "ok" ]; then echo '拉取完成'; else echo '拉取失败' && xxxx; fi
    - PULL_RESULT=""
    - docker pull registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:arm64-latest && PULL_RESULT="ok"
    - if [ "$PULL_RESULT" == "ok" ]; then echo '拉取完成'; else echo '拉取失败' && xxxx; fi
    - PULL_RESULT=""
    - docker pull registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:s390x-latest && PULL_RESULT="ok"
    - if [ "$PULL_RESULT" == "ok" ]; then echo '拉取完成'; else echo '拉取失败' && xxxx; fi
    - PULL_RESULT=""
    - docker pull registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:ppc64le-latest && PULL_RESULT="ok"
    - if [ "$PULL_RESULT" == "ok" ]; then echo '拉取完成'; else echo '拉取失败' && xxxx; fi
    - PULL_RESULT=""
    - docker pull registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-latest && PULL_RESULT="ok"
    - if [ "$PULL_RESULT" == "ok" ]; then echo '拉取完成'; else echo '拉取失败' && xxxx; fi
    - docker images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker tag registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:arm-latest $DOCKER_USERNAME/gitlab-runner-helper:arm-latest
    - docker tag registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:arm64-latest $DOCKER_USERNAME/gitlab-runner-helper:arm64-latest
    - docker tag registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:s390x-latest $DOCKER_USERNAME/gitlab-runner-helper:s390x-latest
    - docker tag registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:ppc64le-latest $DOCKER_USERNAME/gitlab-runner-helper:ppc64le-latest
    - docker tag registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-latest $DOCKER_USERNAME/gitlab-runner-helper:x86_64-latest
    - docker images
    - docker push $DOCKER_USERNAME/gitlab-runner-helper:arm-latest
    - docker push $DOCKER_USERNAME/gitlab-runner-helper:arm64-latest
    - docker push $DOCKER_USERNAME/gitlab-runner-helper:s390x-latest
    - docker push $DOCKER_USERNAME/gitlab-runner-helper:ppc64le-latest
    - docker push $DOCKER_USERNAME/gitlab-runner-helper:x86_64-latest
