stages:
  - docker-build-before
  - docker-build

docker-build-before:
  stage: docker-build-before
  image: python:latest
  script:
    - pip install requests
    - python tags.py
    - ls
  artifacts:
    paths:
      - tags.sh

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  needs:
    - job: docker-build-before
      artifacts: true
  script:
    - docker images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - ls
    - chmod +x tags.sh
    - chmod +x tags_push.sh
    - ./tags.sh
    - docker images
    - docker images "$DOCKER_USERNAME"
    - ./tags_push.sh
