stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker pull registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v14.10.1
  after_script:
    - docker images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker tag registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v14.10.1 $DOCKER_USERNAME/gitlab-runner-helper:x86_64-v14.10.1
    - docker images
    - docker push $DOCKER_USERNAME/gitlab-runner-helper:x86_64-v14.10.1
